version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stockdb
      - REDIS_URL=redis://redis:6379 #  add redis env here
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: >
      redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: "0.50" # limit Redis to half a CPU

volumes:
  pgdata:
  redisdata:
